version: "3.7"

services:
###########
# PI-HOLE #
###########
  pihole:
    container_name: pihole
    hostname: dckvm-piHole
    image: pihole/pihole:latest
    restart: ${RESTART_POLICY}
    env_file: .env
    volumes:
       - ./pihole/etc-pihole:/etc/pihole
       - ./pihole/etc-dnsmasq.d:/etc/dnsmasq.d
    cap_add:
       - NET_ADMIN
    dns:
      - ${DNS01}
      - ${DNS02}
    environment:
      - DNS1=${DNS01}
      - DNS2=${DNS02}
      - ServerIP=${PIHOLE_IP}
      - DNSMASQ_LISTENING=all
      - WEBPASSWORD=${PIHOLE_PASS}
      - TZ= ${TZ}
      - mac-address=${PIHOLE_MAC}
    network_mode: mainLan

####################
# UNIFI CONTROLLER #
####################
  uniCon:
    image: lscr.io/linuxserver/unifi-controller:latest
    container_name: uniCon
    restart: always
    env_file: .env
    environment:
      - TZ=${TZ}
      - PUID=${PUID}
      - PGID=${PGID}
      - MEM_LIMIT=1024 #optional
      - MEM_STARTUP=1024 #optional
    volumes:
      - /unifi_data/config:/config
    networks:
      mainLan:
        ipv4_address: ${UNIFI_IP}


#############
# PORTAINER #
#############
  portainer:
    image: portainer/portainer-ce
    container_name: mgnt-portainer
    volumes:
      - ${DOCKER_SOCKET}:/var/run/docker.sock
      - ${PORTAINER_DATA}:/data
    ports:
      - ${PORTAINER_PORT_UI}:9000
      - ${PORTAINER_PORT_SSL}:8000
    expose:
      - ${PORTAINER_PORT_UI}
      - ${PORTAINER_PORT_SSL}
    restart: ${RESTART_POLICY}
    labels:
      #- ${UPDATE_ON}
      - com.centurylinklabs.watchtower.enable=true

networks:
  mainLan:
    external: true
